plugin: aws_ec2
# plugin: constructed
# strict: false

regions:
  - eu-west-2

# keyed_groups:
  # - key: tags.Name
  # - prefix: instance_type
  # - key: instance_type
  # - prefix: aws_region
  # - prefix: "distro"
  #   key: ansible_distribution

hostnames:
# A list in order of precedence for hostname variables.
  - ip-address
  # - dns-name
  # - tag:Name
  #  - private-ip-address

filters:
  instance-state-name : running
  # tag:Name:
  #   - Applications.
  #   - Ubuntu

compose:
  ansible_user: "'ec2-user'"

groups:
  master: "'master-node' == (tags.Name)"
  worker: "'worker-node' == (tags.Name)"