- name: Copy the join command
  copy:
    src: join-command
    dest: /tmp/join-command.sh
    mode: 0777

- name: Cluster initialization pre-check
  stat: 
    path:
      /etc/kubernetes/kubelet.conf
  register: status

- name: Join node(s) to cluster
  command: sh /tmp/join-command.sh
  when: status.stat.exists == false
